---
- name: Trying to use the loop concept basicaly
  hosts: node1
  gather_facts: 0
  vars:
    colors:
      - red
      - black
      - blue
      - yellow

  tasks:
    - name: Trying to print the colors
      loop: "{{ colors }}"
      ansible.builtin.debug:
        msg: >
          This is My Favourite Colors: "{{ item }}"

