---
- name: Install the ssh config
  hosts: all
  become: yes
  tasks:
    - name: Currently trying to install the ssh
      ansible.builtin.command:
        echo "{{ lookup('file', '~/.ssh/id_rsa.pub') }}" >> ~/.ssh/authorized_keys
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/authorized_keys
      args:
        executable: /bin/bash

    - name: Verify SSH keys are added
      ansible.builtin.command: cat ~/.ssh/authorized_keys
      register: key_output

    - debug:
        msg: "SSH key successfully added to {{ inventory_hostname }}: {{ key_output.stdout }}"


